In [1]:
import pandas as pd,numpy as np,os

In [2]:
# Import data from processed
processed_data_path=os.path.join(os.path.pardir,'data','processed')
train_data_path=os.path.join(processed_data_path,'train.csv')
test_data_path=os.path.join(processed_data_path,'test.csv')

In [3]:
train_df=pd.read_csv(train_data_path,index_col='PassengerId')
test_df=pd.read_csv(test_data_path,index_col='PassengerId')

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-null int64
Title_Officer         891 non-

In [5]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

In [11]:
# DATA PREPARARTION

In [14]:
X=train_df.loc[:,:'AgeState_Child'].as_matrix().astype(float)

In [18]:
# numpy function that creates flatened 1D arrray
y=train_df['Survived'].ravel()

In [24]:
#upper case X to specify array, and lower case y to specify 1D array or vector
print( X.shape,y.shape)

(891, 32) (891,)


In [25]:
# import from sklearn.model_selection the train_tesst_split
from sklearn.model_selection import train_test_split

In [26]:
# train test split takes argument array of Input features, array of output feature, test_size specifies the percent to split
# train data i.e 0.2 = 20% test data,random_state is like seed value for randomization(for reproducibility)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
print( X_train.shape,y_train.shape)
print( X_test.shape,y_test.shape)

(712, 32) (712,)
(179, 32) (179,)


In [29]:
#checking positive values in train and test data using mean
#average survival rate in train and test
print(y_train.mean(),y_test.mean())

0.38342696629213485 0.3854748603351955


In [30]:
#Building and Evaluating

In [31]:
import sklearn

In [32]:
sklearn.__version__

'0.19.1'

In [33]:
# Import DummyClassifer 
from sklearn.dummy import DummyClassifier
# Create Model using DummyClassifier function and passing the strategy and setting random_state
model_dummy=DummyClassifier(strategy='most_frequent',random_state=0)

In [35]:
#train model using fit function and specifying the i/p features and o/p feature
model_dummy.fit(X_train,y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [37]:
# score function  gives the performance details of the model on test data, default score represents Accuracy
model_dummy.score(X_test,y_test)

0.6145251396648045

In [39]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score
model_dummy.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [40]:
# first argument actual output and second as predicted output
accuracy_score(y_test,model_dummy.predict(X_test))

0.6145251396648045

In [41]:
confusion_matrix(y_test,model_dummy.predict(X_test))

array([[110,   0],
       [ 69,   0]], dtype=int64)

In [42]:
precision_score(y_test,model_dummy.predict(X_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


0.0

In [43]:
recall_score(y_test,model_dummy.predict(X_test))

0.0

# First Kaggle Submission

In [44]:
# getting data as a matrix
test_X=test_df.as_matrix().astype(float)
# making predictions
predictions=model_dummy.predict(test_X)

# creating a pandas dataframe to store the predictions with PassengID
df_submission=pd.DataFrame({'PassengerId':test_df.index,'Survived':predictions})

In [45]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [46]:
submission_data_path=os.path.join(os.path.pardir,'data','external')
submission_file_path=os.path.join(submission_data_path,'df_dummy1.csv')

In [47]:
# index = false to not add an index column in the file
df_submission.to_csv(submission_file_path,index=False)

In [48]:
def get_submission_file(model,file):
    # getting data as a matrix
    test_X=test_df.as_matrix().astype(float)
    # making predictions
    predictions=model.predict(test_X)
    # creating a pandas dataframe to store the predictions with PassengID
    df_submission=pd.DataFrame({'PassengerId':test_df.index,'Survived':predictions})
    submission_data_path=os.path.join(os.path.pardir,'data','external')
    submission_file_path=os.path.join(submission_data_path,file)
    # index = false to not add an index column in the file
    df_submission.to_csv(submission_file_path,index=False)

In [49]:
get_submission_file(model_dummy,'dummy.csv')

# Machine Learning Model

# using Logistic Regression

In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
model=LogisticRegression(random_state=0)

In [53]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [54]:
accuracy_score(y_test,model.predict(X_test))

0.8324022346368715

In [55]:
model.coef_

array([[-0.02833748,  0.0045431 , -0.50072128,  0.6294571 , -0.84669314,
         0.12261951, -0.16861801, -0.38942021,  0.52435133,  1.10097906,
         0.40500935, -0.17994151, -0.29608052,  0.9699488 ,  0.48951883,
        -0.34056863,  0.42622105,  1.21580154,  0.52532086, -1.45889574,
         1.01405023, -0.12222381, -0.48137512,  0.16413234,  0.25175437,
         0.2847403 ,  0.41827199,  0.49843519,  0.46568404,  0.15477978,
         0.38375395,  0.73514505]])

In [57]:
get_submission_file(model,'LRSubmission.csv')

In [67]:
model=LogisticRegression(C=1.0,penalty='l2',random_state=0)

In [68]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [69]:
accuracy_score(y_test,model.predict(X_test))

0.8324022346368715

# Hyperparameter Tuning

In [73]:
# create parameters variable with all the values to try.
parameters={'C':[0.5,1.0,10.0,25.0,100.0,1000.0],'penalty':['l1','l2']}
#import GridSearchCV from sklearn.model_selection
from sklearn.model_selection import GridSearchCV
#create model using GridSearchCV by passing params first the LR model, second param_grid as the parameters dictionary 
#and third, cv value which performs 3 fold cross validation
clf=GridSearchCV(model,param_grid=parameters,cv=3)


In [74]:
clf.fit(X_train,y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.5, 1.0, 10.0, 25.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [75]:
# to view the best param
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [76]:
clf.best_score_

0.8314606741573034

In [78]:
# Feature Normalizer : MinMaxScaler and Feature Standardizer: StandardScaler
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [83]:
# fit_transform method of scaler first fits data and then transforms it to 0-1 scale
scaler=MinMaxScaler()
X_train_scaled=scaler.fit_transform(X_train)

In [85]:
X_test_scaled=scaler.transform(X_test)

# Feature Standardization

In [86]:
# fit_transform method of scaler first fits data and then transforms it to 0-1 scale
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [106]:
# create parameters variable with all the values to try.
parameters={'C':[0.16,0.25,0.5,1.0,10.0,25.0,100.0,1000.0],'penalty':['l1','l2']}
#create model using GridSearchCV by passing params first the LR model, second param_grid as the parameters dictionary 
#and third, cv value which performs 3 fold cross validation
clf=GridSearchCV(model,param_grid=parameters,cv=3)
clf.fit(X_train_scaled,y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.16, 0.25, 0.5, 1.0, 10.0, 25.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [109]:
clf.best_params_

{'C': 0.16, 'penalty': 'l1'}

In [107]:
clf.best_score_

0.827247191011236

In [108]:
clf.score(X_test_scaled,y_test)

0.8268156424581006

# Model Persistence

In [110]:
import pickle

In [118]:
#defining file path
scaler_file_path=os.path.join(os.path.pardir,'models','scaler.pkl')
model_file_path=os.path.join(os.path.pardir,'models','model.pkl')

In [119]:
with open(model_file_path,'wb') as file:
    pickle.dump(clf,file)

with open(scaler_file_path,'wb') as file:
    pickle.dump(scaler,file)

#  Loading from Pickle

In [123]:
with open(model_file_path,'rb') as file:
    clf_loaded=pickle.load(file)

with open(scaler_file_path,'rb') as file:
    scaler_loaded=pickle.load(file)

In [124]:
clf_loaded

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.16, 0.25, 0.5, 1.0, 10.0, 25.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [125]:
scaler_loaded

StandardScaler(copy=True, with_mean=True, with_std=True)

In [128]:
clf_loaded.score(X_test_scaled,y_test)

0.8268156424581006